apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IncludeMutationWebhook=true
  creationTimestamp: null
  labels:
    app: aning-podinfo
    project: default
  name: aning-podinfo
  namespace: argocd
spec:
  destination:
    namespace: ap-tf-exemplar
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: app
    helm:
      releaseName: aning-podinfo
      valueFiles:
      - $valuesRepo/services/ap-podinfo/values.yaml
    repoURL: http://chartmuseum:8080
    targetRevision: v7.3.1
  - ref: valuesRepo
    repoURL: https://github.com/angelahning/traffic-services
    targetRevision: main
  syncPolicy: {}
