apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IncludeMutationWebhook=true
  creationTimestamp: null
  labels:
    app: shulin-exemplar
    project: default
  name: shulin-exemplar
  namespace: argocd
spec:
  destination:
    namespace: ap-exemplar-ad
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: app
    helm:
      releaseName: exemplar-ad-service-au-qa
      valueFiles:
      - $valuesRepo/services/shulin-exemplar/historical-ap-values.yaml
    repoURL: http://chartmuseum:8080
    targetRevision: v7.3.1
  - ref: valuesRepo
    repoURL: https://github.com/angelahning/traffic-services
    targetRevision: shulin/test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30m
        factor: 1
        maxDuration: 30m
      limit: 3
    syncOptions:
    - Validate=true
    - PrunePropagationPolicy=foreground
    - CreateNamespace=true
    - PruneLast=false
    - Prune=false
    - PreserveResourcesOnDeletion=true
