apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IncludeMutationWebhook=true
  creationTimestamp: null
  labels:
    app: shulin-exemplar
    project: default
  name: shulin-exemplar
  namespace: argocd
spec:
  destination:
    namespace: ap-exemplar-ad
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/angelahning/traffic-services.git
    targetRevision: shulin/test
    path: charts/service-chart
    helm:
      valueFiles:
        - $valuesRepo/services/shulin-exemplar/historical-ap-values.yaml
      releaseName: shulin-exemplar
  syncPolicy:
    syncOptions:
    - Validate=true
    - PrunePropagationPolicy=foreground
    - CreateNamespace=true
    - PruneLast=false
    - Prune=false
    - PreserveResourcesOnDeletion=true
