chart:
  name: app
  version: v7.3.1
configMap:
  env:
    AD_SERVICE_ADDR: exemplar-ad-service-au-qa.ap-exemplar-ad:8080
    CART_SERVICE_ADDR: exemplar-cart-service-au-qa.ap-exemplar-cart:8080
    CELL_ID: beta-apse2-v2
    CHECKOUT_SERVICE_ADDR: exemplar-checkout-service-au-qa.ap-exemplar-checkout:8080
    CURRENCY_SERVICE_ADDR: exemplar-currency-service-au-qa.ap-exemplar-currency:8080
    CYMBAL_BRANDING: "true"
    DD_TRACE_DEBUG: "false"
    DD_TRACE_STARTUP_LOGS: "false"
    ENABLE_PROFILER: "0"
    ENABLE_TRACING: "1"
    PORT: "8080"
    PRODUCT_CATALOG_SERVICE_ADDR: exemplar-productcatalog-service-au-qa.ap-exemplar-productcatalog:8080
    RECOMMENDATION_SERVICE_ADDR: exemplar-recommendation-service-au-qa.ap-exemplar-recommendation:8080
    SHIPPING_SERVICE_ADDR: exemplar-shipping-service-au-qa.ap-exemplar-shipping:8080
deployment:
  container:
    healthChecks:
      livenessProbe:
        httpGet:
          httpHeaders:
          - name: Cookie
            value: shop_session-id=x-liveness-probe
          path: /_healthz
          port: 8080
        initialDelaySeconds: 10
      readinessProbe:
        httpGet:
          httpHeaders:
          - name: Cookie
            value: shop_session-id=x-readiness-probe
          path: /_healthz
          port: 8080
        initialDelaySeconds: 10
    image: 361053881171.dkr.ecr.ap-southeast-2.amazonaws.com/k8s/pe/platform-exemplar
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: "1"
        memory: 512Mi
  datadog:
    apm:
      enabled: false
    enabled: true
    env: au-qa
    logging:
      enabled: true
  replicaCount: 2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
    type: RollingUpdate
hpa:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 20
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      - periodSeconds: 15
        type: Pods
        value: 4
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  cpu: 80
  enabled: true
  maxReplicas: 5
labels:
  admission.datadoghq.com/enabled: "true"
  component: frontend
  deployment_method: Helm
  lang: go
  lang_version: unset
  repo: platform-exemplar
  runtime: unset
  service_name: ap-exemplar-frontend
  singleton: false
  team: kompute
  team_slack_channel: kompute-support
  tier: 3
networkPolicy:
  enabled: false
ports:
- name: http-app
  port: 8080
  protocol: TCP
  targetPort: 8080
service:
  name: ""
  tier: 3
slug: ap-exemplar-frontend
version: frontend.main.384
virtualService:
  enabled: true
  fqdn:
  - exemplar-frontend-qa.au.kompute.afterpay-beta.com
  - shop.au.afterpay-beta.com
  gatewayOverride:
  - istio-system/gateway-default
  portNumber: 8080
